apiVersion: apps/v1
kind: Deployment

metadata:
  name: prestamos-backend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: prestamos-backend

  template:
    metadata:
      labels:
        app: prestamos-backend

    spec:
      containers:
        - name: prestamos-backend

          image: prestamos-backend:latest

          ports:
            - containerPort: 3000

          env:
            - name: DB_HOST
              value: "ep-aged-fire-apmmplfh-pooler.c-7.us-east-1.aws.neon.tech"

            - name: DB_PORT
              value: "5432"

            - name: DB_USERNAME
              value: "neondb_owner"

            - name: DB_PASSWORD
              value: "npg_1ejGt6RSAYiE"

            - name: DB_DATABASE
              value: "neondb"

            - name: JWT_SECRET
              value: "mi_clave_secreta"

            - name: RECAPTCHA_SECRET
              value: "6LfRwRUtAAAAAJw61FcKYqVSPvaatcLU0AbQE68D"